### ISSUE TITLE
Tests hang sometimes

### ISSUE THREAD

**Issue by churkin** [sijosyn/testcafe-browser-provider-crossbrowsertesting#1]
Good job @sijosyn! I've tried your plugin and sometimes my tests do not start. They hang before running. Have you come across this?

**Comment by sijosyn** [comment]
Hi @churkin. I have never come across the issue where the tests would not start or hang before running. I have released v1.0.1 with some bug fixes and updated dependency libraries to the latest versions. Could you please give the new version a try? If you are still seeing those issues, could you provide some more details for me to debug the issue? I have tested this on Mac 10.13 and it works fine for me. Thanks.

**Comment by churkin** [comment]
Hi @sijosyn, I'll look into this problem in depth soon. Anyway, you've made a good job, and TestCafe team will be happy to inform our community about it. Thanks a lot!
