### ISSUE TITLE
[Solved] ERROR The specified "crossbrowsertesting" browser provider was not found

### ISSUE THREAD

**Issue by bennymeade** [sijosyn/testcafe-browser-provider-crossbrowsertesting#6]
Hello @sijosyn

I've installed this package to my TestCafe project and updated **CBT_TUNNELS_USERNAME and CBT_TUNNELS_AUTHKEY** in src/index.js in the 4 different sections:
```
* function doRequest
* function startBrowser
* openBrowser
* CBTConnector.start

```
My .bash_profile file looks like this:

```
# Setting PATH for Python 3.7
# The original version is saved in .bash_profile.py save
PATH="/Library/Frameworks/Python.framework/Versions/3.7/bin:${PATH}"
export PATH
export CBT_TUNNELS_USERNAME="me@work.com"
export CBT_TUNNELS_AUTHKEY="123xyz"

```
Error when I check the available browsers:
```
$ testcafe -b crossbrowsertesting
ERROR The specified "crossbrowsertesting" browser provider was not found.
```
Is there something obviously wrong that I'm doing here?

**Comment by bennymeade** [comment]
Solution is same as noted here nightmare version:

https://github.com/ryx/testcafe-browser-provider-nightmare/issues/6#issuecomment-283643671

"Please check that `testcafe` and `testcafe-browser-provider-nightmare` are installed locally both (or globally both). I've reproduced the issue only if I use locally installed `testcafe`, but the provider is installed globally (via `npm install -g testcafe-browser-provider-nightmare`)"

**Comment by sijosyn** [comment]
@bennymeade Glad that you found the solution for this issue. I'll go ahead close this issue as its marked as solved.
