### ISSUE TITLE
Capabilities setting for process.env.CBT_RECORD_VIDEO not being picked up

### ISSUE THREAD

**Issue by bennymeade** [sijosyn/testcafe-browser-provider-crossbrowsertesting#7]
```
index.js
if (process.env.CBT_RECORD_VIDEO)
                    capabilities.record_video = process.env.CBT_RECORD_VIDEO.match(/true/i);
```
Even though I'm setting env variable as: `export CBT_RECORD_VIDEO="true"`

The capabilities are not picking up this setting and therefore not recording my tests:

```
Capabilities requested for this Selenium test:

browserName = "Chrome"
version = "70"
platform = "Mac OSX 10.13"
name = "TestCafe test run j_06KK1"
javascriptEnabled = "true"
```

**Comment by sijosyn** [comment]
@bennymeade I haven't tested this functionality myself. The CBT_RECORD_VIDEO capability was added by @radTuti in this PR - https://github.com/sijosyn/testcafe-browser-provider-crossbrowsertesting/pull/2#issue-189038183 . (see his comment there -- i have noticed that recording of video and/or network is dependent on the browser combination)

**Comment by bennymeade** [comment]
Thanks for the quick reply @sijosyn That's fine, I can certainly manage without all videos recorded. Your 'testcafe-browser-provider-crossbrowsertesting' package is literally the only work on the web done to connect these two tools, so many thanks for doing this.

**Comment by radTuti** [comment]
@bennymeade were you able to verify that `CBT_RECORD_VIDEO` was present in `process.env` at the start of the test run?

p.s. _i have not used testcafe in a bit_

**Comment by bennymeade** [comment]
@radTuti I've revisited this this morning and now videos are being recorded, I've made no changes to my code since! Tested with "crossbrowsertesting:Chrome@70:Mac OSX 10.13" and "crossbrowsertesting:Chrome@43:Windows 10". Thanks for your response.

```
Capabilities requested for this Selenium test:

browserName = "Chrome"
version = "70"
platform = "Mac OSX 10.13"
name = "TestCafe test run kxeJ0aO"
record_video = "true"
javascriptEnabled = "true"
```
